# Замени на данные из своего личного кабинета SonarCloud (Project -> Information)
sonar.projectKey=tokendeff
sonar.organization=ivan-bir

# Пути
sonar.sources=.
sonar.exclusions=**/*_test.go,**/testdata/**
sonar.go.coverage.reportPaths=coverage.out